### PR TITLE
Add AMQP topic exchange handling

### PR DESCRIPTION
**Pull request by Gnucki**
The main goal of this pull request is to allow use of AMQP topic exchange (https://www.rabbitmq.com/tutorials/tutorial-five-php.html) but certainly allow much more.

Integration tests on a real app: DONE

_Note: I made the implementation in the idea of only impacting this repository and avoiding breaking changes but one can probably imagine a better implementation impacting several repositories with some breaking changes._

#22

### CODE REVIEW

**Comment by nipeharefa** [comment]
+1 for this PR.

**Comment by Gnucki** [comment]
@drgomesp
Nice!
I'm in vacations this week so it's going to be a bit hard to do it but I can make it next monday.

**Comment by Gnucki** [comment]
@drgomesp It took me a little time because I had some trouble to test with my previous real example. In fact, it seems that there is a [little bug](https://github.com/php-enqueue/enqueue-dev/issues/621) in `QueueInteropTransportFactory.php`.

I'm going to make a PR for that too.

**Comment by drgomesp** [comment]
@Gnucki thanks for your efforts 👍

**Pull request merged**
