### PR TITLE
Fix DSN query handling

### PR DESCRIPTION
**Pull request by Gnucki**

### CODE REVIEW

**Comment by Gnucki** [comment]
Seems there is an error in tests execution which is not related to my commit.

**Comment by sroze** [comment]
This just has been fixed by #7. But thank you for your pull-request :)

**Comment by sroze** [comment]
@Gnucki can you try `master` and tell us if it works well for you?

**Comment by Gnucki** [comment]
No problem!
Tests are now passing for me on master.

**Pull request closed without merging**
