### PR TITLE
Support for EnqueueBundle 0.9.x-dev

### PR DESCRIPTION
**Pull request by drgomesp**
This is an attempt to bump versions in order to support `enqueue/enqueue-bundle[0.9.x-dev]`.

* Fixed `MessageBusProcessor` tests
* Fixed `QueueInterop` related tests and refactored code
* Refactored `AmqpContextManager`
* Refactored `ContextManager` interface
* Bumped versions

### CODE REVIEW

**Comment by makasim** [comment]
Looks good

**Comment by drgomesp** [comment]
Will this be tagged or just merged to `master` until there's a stable version?

**Comment by makasim** [comment]
@drgomesp the serializer was fixed in https://github.com/php-enqueue/messenger-adapter/pull/29, coild you please resolve issues and I'll merge it.

**Comment by drgomesp** [comment]
@makasim done.

**Pull request merged**
