### PR TITLE
RepeatMessage

### PR DESCRIPTION
**Pull request by scarbo87**
Added extension RepeatMessage

### CODE REVIEW

**Comment by scarbo87** [comment]
@sroze , thanks for the review, I'll fix the notes this weekend.

**Comment by scarbo87** [comment]
yes

**Comment by sroze** [comment]
I'll take it as "one of you can take it over" then 😄 

Thank you for your work on it so far anyway 👍

**Comment by drgomesp** [comment]
Closing this as it's old. @scarbo87 if you still want this, please re-open the PR.

**Pull request closed without merging**
