### PR TITLE
Removing unmaintained message

### PR DESCRIPTION
**Pull request by weaverryan**
I believe that there are enough people willing to take on maintenance for this library from @makasim. I think we should figure out who exactly that is, and then we can remove this message.

I am not an expert on matters of queueing, but I am willing to help maintain this library. I would love a few other people :).

@drgomesp are you available and willing to help maintain this library?
@shulard are you available and willing to help maintain this library?

Is anyone else interested? 

Thanks!

### CODE REVIEW

**Comment by devrck** [comment]
I could lend a hand :smile:

**Comment by drgomesp** [comment]
I'm currently on holidays but I'll be back on active duty soon and help out.

**Comment by weaverryan** [comment]
Awesome! @devrck you've already been helping on some PR's (thanks!) - we should also see if we can triage/cleanup/close/fix old issues. Btw, if you're on Symfony Slack, you can ping me there anytime.

**Comment by shulard** [comment]
@weaverryan I'm interesting to help maintain this library. I'm not a queuing expert but I've used that adapter on different projects.

**Comment by weaverryan** [comment]
Merging to remove this message. This is not a huge library, but let's work together to see if we can keep it maintained - the bridge to Enqueue is a great thing for Messenger.

**Comment by sroze** [comment]
Thank you Ryan!

**Pull request merged**
